-- Profiles Table
CREATE TABLE public.profiles (
  id uuid NOT NULL REFERENCES auth.users ON DELETE CASCADE,
  username text,
  avatar_url text,
  bio text,
  resume_url text,
  PRIMARY KEY (id)
);
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile." ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update their own profile." ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Skills Table
CREATE TABLE public.skills (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  proficiency integer NOT NULL,
  type text,
  icon_class text
);
ALTER TABLE public.skills ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public can view skills." ON public.skills FOR SELECT USING (true);
CREATE POLICY "Admin can manage skills." ON public.skills FOR ALL USING (auth.uid() = 'YOUR_ADMIN_USER_ID'); -- Replace with your admin user ID

-- Projects Table
CREATE TABLE public.projects (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text,
  thumbnail_url text,
  live_url text,
  source_url text,
  is_public boolean DEFAULT false,
  display_order integer DEFAULT 0
);
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public can view public projects." ON public.projects FOR SELECT USING (is_public = true);
CREATE POLICY "Admin can manage projects." ON public.projects FOR ALL USING (auth.uid() = 'YOUR_ADMIN_USER_ID'); -- Replace with your admin user ID

-- Posts Table
CREATE TABLE public.posts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  content text,
  excerpt text,
  tags text[],
  is_published boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now()
);
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public can view published posts." ON public.posts FOR SELECT USING (is_published = true);
CREATE POLICY "Admin can manage posts." ON public.posts FOR ALL USING (auth.uid() = 'YOUR_ADMIN_USER_ID'); -- Replace with your admin user ID

-- Social Links Table
CREATE TABLE public.social_links (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  url text NOT NULL
);
ALTER TABLE public.social_links ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public can view social links." ON public.social_links FOR SELECT USING (true);
CREATE POLICY "Admin can manage social links." ON public.social_links FOR ALL USING (auth.uid() = 'YOUR_ADMIN_USER_ID'); -- Replace with your admin user ID

-- Messages Table
CREATE TABLE public.messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text NOT NULL,
  message text NOT NULL,
  created_at timestamp with time zone DEFAULT now()
);
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admin can view messages." ON public.messages FOR SELECT USING (auth.uid() = 'YOUR_ADMIN_USER_ID'); -- Replace with your admin user ID
CREATE POLICY "Anyone can send a message." ON public.messages FOR INSERT WITH CHECK (true);

-- Audit Log Table
CREATE TABLE public.audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users,
  action text NOT NULL,
  details jsonb,
  created_at timestamp with time zone DEFAULT now()
);
ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admin can view audit logs." ON public.audit_log FOR SELECT USING (auth.uid() = 'YOUR_ADMIN_USER_ID'); -- Replace with your admin user ID
